# Generated by Django 5.2.16 on 2026-07-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_programactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='partner',
            name='region',
            field=models.CharField(blank=True, help_text='State, province, or region.', max_length=128),
        ),
        migrations.AddField(
            model_name='partnerclick',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='partnerclick',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='partnerclick',
            name='region',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
