# Generated by Django 5.2.16 on 2026-07-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_partner_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='continent',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='partnerclick',
            name='continent',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
