# Generated by Django 5.2.16 on 2026-07-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_partner_notifications_and_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='country_code',
            field=models.CharField(blank=True, help_text='ISO country code for forms and payouts.', max_length=8),
        ),
        migrations.AddField(
            model_name='partner',
            name='payment_details_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='partner',
            name='payment_details',
            field=models.TextField(blank=True, help_text='Formatted payout details for admin review (auto-generated).'),
        ),
    ]
