# Generated by Django 5.2.17 on 2026-10-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0008_promo_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="discount_code_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this personal code stops being valid. Leave blank if no end date is set yet.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="discount_code",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Personal store discount code. Staff can clear it or issue a new one.",
                max_length=16,
                null=True,
                unique=True,
            ),
        ),
    ]
