# Generated by Django 5.2.17 on 2026-10-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0009_partner_discount_code_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="commission_locked",
            field=models.BooleanField(
                default=False,
                help_text="If checked, the commission percentage will not auto-update based on sales.",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="commission_tier",
            field=models.CharField(
                choices=[
                    ("rising", "Rising"),
                    ("established", "Established"),
                    ("ambassador", "Ambassador"),
                ],
                default="rising",
                help_text="Automatically assigned based on total sales. Admins can override.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="discount_code",
            field=models.CharField(
                blank=True,
                help_text="Personal store discount code. Staff can clear it or issue a new one.",
                max_length=16,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paypal", "PayPal"),
                    ("bank_transfer", "Bank Transfer"),
                    ("venmo", "Venmo"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="partnerpayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("paypal", "PayPal"),
                    ("bank_transfer", "Bank Transfer"),
                    ("venmo", "Venmo"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
    ]
