"""Map country names / ISO codes to continent names."""

_COUNTRY_CONTINENT = {
    # North America
    "US": "North America",
    "USA": "North America",
    "UNITED STATES": "North America",
    "CA": "North America",
    "CANADA": "North America",
    "MX": "North America",
    "MEXICO": "North America",
    # Europe
    "GB": "Europe",
    "UK": "Europe",
    "UNITED KINGDOM": "Europe",
    "FR": "Europe",
    "FRANCE": "Europe",
    "DE": "Europe",
    "GERMANY": "Europe",
    "IT": "Europe",
    "ITALY": "Europe",
    "ES": "Europe",
    "SPAIN": "Europe",
    "NL": "Europe",
    "NETHERLANDS": "Europe",
    "SE": "Europe",
    "SWEDEN": "Europe",
    "NO": "Europe",
    "NORWAY": "Europe",
    "CH": "Europe",
    "SWITZERLAND": "Europe",
    "IE": "Europe",
    "IRELAND": "Europe",
    "PT": "Europe",
    "PORTUGAL": "Europe",
    "PL": "Europe",
    "POLAND": "Europe",
    # Asia
    "CN": "Asia",
    "CHINA": "Asia",
    "JP": "Asia",
    "JAPAN": "Asia",
    "IN": "Asia",
    "INDIA": "Asia",
    "KR": "Asia",
    "SOUTH KOREA": "Asia",
    "KOREA": "Asia",
    "SG": "Asia",
    "SINGAPORE": "Asia",
    "AE": "Asia",
    "UAE": "Asia",
    "UNITED ARAB EMIRATES": "Asia",
    "SA": "Asia",
    "SAUDI ARABIA": "Asia",
    "PH": "Asia",
    "PHILIPPINES": "Asia",
    "TH": "Asia",
    "THAILAND": "Asia",
    "VN": "Asia",
    "VIETNAM": "Asia",
    "MY": "Asia",
    "MALAYSIA": "Asia",
    "ID": "Asia",
    "INDONESIA": "Asia",
    # Oceania
    "AU": "Oceania",
    "AUSTRALIA": "Oceania",
    "NZ": "Oceania",
    "NEW ZEALAND": "Oceania",
    # South America
    "BR": "South America",
    "BRAZIL": "South America",
    "AR": "South America",
    "ARGENTINA": "South America",
    "CO": "South America",
    "COLOMBIA": "South America",
    "CL": "South America",
    "CHILE": "South America",
    "PE": "South America",
    "PERU": "South America",
    # Africa
    "NG": "Africa",
    "NIGERIA": "Africa",
    "ZA": "Africa",
    "SOUTH AFRICA": "Africa",
    "EG": "Africa",
    "EGYPT": "Africa",
    "KE": "Africa",
    "KENYA": "Africa",
    "GH": "Africa",
    "GHANA": "Africa",
    "MA": "Africa",
    "MOROCCO": "Africa",
}


def country_to_continent(country: str) -> str:
    if not country:
        return ""
    key = country.strip().upper()
    return _COUNTRY_CONTINENT.get(key, "")
